version: '2'
networks:
  prodnetwork:
    driver: bridge

volumes:
  registry-stuff:
    driver: local
    
services:
  fluentd:
    extends:
      file: extends.yml
      service: fluentd
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  elasticsearch:
    extends:
      file: extends.yml
      service: elasticsearch
  kibana:
    extends:
      file: extends.yml
      service: kibana
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  nginx:
    extends:
      file: extends.yml
      service: nginx
    depends_on:
      - fluentd
    links:
      - fluentd
